services:
  - type: web
    name: manga-gen-api
    env: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_conf.py main:app
    branch: main
